name: Deploy To Production Server

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to production server
              uses: appleboy/ssh-action@v0.1.7
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  script: |
                      # Переход в директорию проекта
                      cd /opt/rkc-gazik-quiz-backend

                      # Сохранение текущего коммита для возможного отката
                      CURRENT_COMMIT=$(git rev-parse HEAD)
                      echo "Current commit: $CURRENT_COMMIT"

                      # Обновление кода через git
                      git pull https://${{ secrets.GIT_TOKEN }}@github.com/${{ github.repository }}.git main

                      # Создание venv если его нет
                      if [ ! -d ".venv" ]; then
                        python3 -m venv .venv
                      fi

                      # Активация виртуального окружения
                      source .venv/bin/activate

                      # Установка/обновление зависимостей
                      pip install -r requirements.txt

                      # Проверка кода на ошибки (например, синтаксис)
                      python3 -m py_compile main.py                      # Остановка сервиса
                      echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl stop rkc_gazification_quiz.service

                      # Запуск сервиса
                      echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl start rkc_gazification_quiz.service

                      # Проверка статуса сервиса
                      sleep 5
                      if echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl is-active --quiet rkc_gazification_quiz.service; then
                        echo "Service started successfully"
                        echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl enable rkc_gazification_quiz.service
                      else
                        echo "Service failed to start, rolling back..."
                        # Откат к предыдущему коммиту
                        git reset --hard $CURRENT_COMMIT
                        
                        # Переустановка зависимостей на случай если они изменились
                        source .venv/bin/activate
                        pip install -r requirements.txt
                        
                        # Повторный запуск с предыдущей версией
                        echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl start rkc_gazification_quiz.service
                        
                        # Проверка что откат сработал
                        if echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl is-active --quiet rkc_gazification_quiz.service; then
                          echo "Rollback successful, service is running with previous version"
                        else
                          echo "Critical error: service failed to start even after rollback"
                          exit 1
                        fi
                        exit 1
                      fi

                      # Финальная проверка логов
                      echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S journalctl -u rkc_gazification_quiz.service --no-pager -n 10
